# MinIO Deployment Configuration
# This deployment sets up a single MinIO instance for object storage
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.service: minio
  name: minio
spec:
  # Run a single replica of MinIO
  replicas: 1
  selector:
    matchLabels:
      io.service: minio
  template:
    metadata:
      labels:
        io.service: minio
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - >
              minio server /data --console-address ':9001' & 
              sleep 5;
              mc alias set myminio http://localhost:9000 admin password;
              mc mb myminio/warehouse --ignore-existing;
              tail -f /dev/null
          env:
            # Environment variables for MinIO configuration
            - name: MINIO_REGION
              value: us-east-1
            - name: MINIO_ROOT_PASSWORD
              value: password
            - name: MINIO_ROOT_USER
              value: admin
          # Use official MinIO image from Quay.io
          image: quay.io/minio/minio
          name: minio
          ports:
            # MinIO API port
            - containerPort: 9000
              protocol: TCP
            # MinIO Console port
            - containerPort: 9001
              protocol: TCP
      # Ensure container restarts if it fails
      restartPolicy: Always
